Repository Spazzy757/ephemeral-enforcer, pull requests merged in 2020-10, with the labels that each got.

#20 Updated the logic for the logging to reduce duplicated code
  README.md
  pkg/workloadkiller/workloadkiller.go
Labels: hacktoberfest-accepted

#23 Refactored to use label selectors to skip resources
  README.md
  manifests/base/deployment.yaml
  pkg/helpers/helpers.go
  pkg/helpers/helpers_test.go
  pkg/workloadkiller/workloadkiller.go
  pkg/workloadkiller/workloadkiller_test.go
Labels: enhancement

#24 Removed need for wait script
  .github/workflows/actions.yaml
  ci/check-deployment.sh
Labels: bug
